### ISSUE TITLE
Slash-heroku is using a deprecated API v2 endpoint

### ISSUE THREAD

**Issue by dmcinnes** [atmos/slash-heroku#28]
Hello @atmos !

Just as a reminder: earlier this year we've announced that [API v2 is being sunset on April 15, 2017](https://devcenter.heroku.com/changelog-items/862).

Slash-heroku is hitting [v2's `/apps/:id/logs` endpoint](https://github.com/atmos/slash-heroku/blob/f2a88bcb56616985acf15b11c93fdaf2783735d0/app/models/heroku_api.rb#L13). [V3's Log Session create](https://devcenter.heroku.com/articles/platform-api-reference#log-session-create) should be more or less equivalent, though if there's some differences in the usage, let me know and I will see what we can do.

Strangely I also see some calls to v2's `/apps/:id/releases/new` on the "Heroku ChatOps for Slack" registered client, maybe an old version?

Thanks!

**Comment by atmos** [comment]
@dmcinnes Yeah, there's two installs. One on my domain and one for work.

**Comment by atmos** [comment]
We removed logs support.

**Comment by dmcinnes** [comment]
Thanks!
